##NOTEBOOK O0- Basics of tensors
A tf.Tensor represents a multidimensional array of elements.

In [ ]:
import tensorflow as tf
print(tf.__version__) #to check the version of tensorflow which you have

2.8.2


In [ ]:
#create a scalar
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10, 7], 
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.], 
                            [3., 2.], 
                            [8., 9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim 

2

In [ ]:
#create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
     ], 
    [
        [7, 8, 9],
        [10, 11, 12]
    ], 
    [
        [13, 14, 15], 
        [16, 17, 18]
     ]
                      ])
tensor
#this tensor has 3 elements, and each element has 2 rows and 3 columns, so we expect the tensor to have shape (3, 2, 3)
#elements can be separated by commas

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changeable = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#tf.variable allows you to change the value of your tensor using the assign method

changeable[0].assign(7) 
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape = (3, 2))

In [ ]:
#shuttle a tensor
#create a tensor
not_shuffled = tf.constant([[10, 7], 
                            [5, 8], 
                            [3, 4]])
not_shuffled.ndim

2

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
#press cntrl+shift to get what values a function takes in tensorflow
# set-seed sets the seed at global level and seed sets it at operational level
tf.random.set_seed(42)
not_shuffled = tf.random.shuffle(not_shuffled, seed = 42)
print(not_shuffled)

tf.Tensor(
[[10  7]
 [ 5  8]
 [ 3  4]], shape=(3, 2), dtype=int32)


#Other Ways to Create Tensors

In [ ]:
#create a tensor of all ones
tf.ones([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros
tf.zeros(shape = (3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#Turn NumpyArrays into Tensors
 -main difference is tensors can be run faster on a GPU than numpy arrays, otherwise they are very similar

In [ ]:
#create a numpy array
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A       

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (3, 2, 4))
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

#Getting more Information from our tensors


*   Shape
*   Rank
*   Dimension/Axis
*   Size





In [ ]:
from tensorflow.python.ops.gen_array_ops import rank_eager_fallback
#create a rank-4 tensor

rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor
rank_4_tensor[0]
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions of tensor:", rank_4_tensor.ndim)
print("Shape of our tensor:", rank_4_tensor.shape)
print("Elements along the zeroth axis of our tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of our tensor:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())  #add the .numpy() to get the number of elements without the extra information






Datatype of every element: <dtype: 'float32'>
Number of dimensions of tensor: 4
Shape of our tensor: (2, 3, 4, 5)
Elements along the zeroth axis of our tensor: 2
Elements along the last axis of our tensor: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


#Indexing on Tensors


In [ ]:
#Get the first 2 elements of every dimension

rank_4_tensor[:2, :2, :2, :2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each index except the last one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

#Reshaping tensors

In [ ]:
#create a rank 2 tensor
tensor2 = tf.zeros(shape = (3, 3))
tensor2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:

#get the last element in each row; or in other words get the element in the last column in every row
tensor2[:, -1]


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [ ]:
tensor3 = tensor2[..., tf.newaxis]  #... means every axis before this one
tensor3

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
tf.expand_dims(tensor2, axis = -1)  #-1 means expand the final axis


<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

#Manipulating tensors (Tensor operations)

Basic *, +, /, -
tf.reshape() 
tf.transpose()
tf.matmul()
tf.tensordot()
@

In [ ]:
tensor = tf.constant([[10, 7], [4, 3], [5, 9]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  3],
       [ 5,  9]], dtype=int32)>

In [ ]:
tensor+ 10  #keep in mind that the original tensor remains unchanged


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 13],
       [15, 19]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  30],
       [ 50,  90]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-6, -7],
       [-5, -1]], dtype=int32)>

In [ ]:
#We can also use the tensorflow built-in functions

tf.multiply(tensor, 10)  #use this if you want your code to run faster

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  30],
       [ 50,  90]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 13],
       [15, 19]], dtype=int32)>

In [ ]:
#In machine learning, matrix multiplication is one of the most common operations
tensor = tf.constant([[10, 10], [2, 2]])
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  2]], dtype=int32)>

In [ ]:
tf.matmul(tensor, tensor)   #this gives you the dot-product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 120],
       [ 24,  24]], dtype=int32)>

In [ ]:
tensor*tensor  #this is element-wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 100],
       [  4,   4]], dtype=int32)>

In [ ]:
tensor @ tensor   #also does a dot-product, this is the python method

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 120],
       [ 24,  24]], dtype=int32)>

In [ ]:
tensor = tf.constant([[10, 7], [4, 3], [5, 9]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  3],
       [ 5,  9]], dtype=int32)>

In [ ]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  4,  5],
       [ 7,  3,  9]], dtype=int32)>

In [ ]:
#we can use 16-bit precision instead of the default 32-bit so that GPU calculations are performed faster
#may not matter much on tensors of small size but the improvement will be significant for tensors of larger sizes

A = tf.constant([10.5, 3.2])
A.dtype

tf.float32

In [ ]:
B= tf.constant([10, 5])
B.dtype

tf.int32

In [ ]:
A = tf.cast(A, dtype=tf.float16)
A.dtype

tf.float16

#Aggregating tensors


*   Get the absolute
*  Get a minimum
*Get a maximum
*Get a mean value of the tensor etc

In [ ]:
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#create a tensor wit random numbers between 0 and 100 with 50 values

E = tf.constant(np.random.randint(0, 100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 82, 36, 24, 40, 89, 93, 64, 85, 17,  6,  0, 95, 40,  4, 66, 92,
       56, 73, 38, 74, 22, 11, 91, 40, 47, 19, 43, 25, 54, 24, 46, 71, 42,
       43, 15, 88, 99, 38, 13, 29, 93, 21, 39, 10,  2, 45, 45, 14,  3])>

In [ ]:
# Find the minimum
min = tf.reduce_min(E).numpy()
min

0

In [ ]:
#find the maximum
max = tf.reduce_max(E).numpy()
max

99

In [ ]:
mean = tf.reduce_mean(E).numpy()
mean

50

In [ ]:
sum = tf.reduce_sum(E).numpy()
sum

2520

In [ ]:
#find variance of a tensor

#tf.reduce_variance() won't work on tensors with dtype  = int . See code cell below. Also variance and std needs access to the tf.math() library 


import tensorflow_probability as tfp

tfp.stats.variance(E).numpy()


869.88837

In [ ]:
E = tf.cast(E, dtype = tf.float32)
tf.math.reduce_variance(E).numpy()



869.88837

In [ ]:
tf.math.reduce_std(E).numpy()

29.49387

#Find the positional maximum and minimum


*   argmin
*   argmax



In [ ]:
#Create a new tensor
tf.random.set_seed(42)
rand= tf.random.uniform(shape=[50])
rand

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#get the index of the maximum value
tf.argmax(rand).numpy()

42

In [ ]:
#get the max value itself
rand[tf.argmax(rand)].numpy()

0.9671384

In [ ]:
tf.reduce_max(rand)


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
assert tf.reduce_max(rand) == rand[tf.argmax(rand)] #output no error if this is true

#another way to check if this is true:

(tf.reduce_max(rand) == rand[tf.argmax(rand)]).numpy() 

#output true if the equality is true, nevermind that l keep putting numpy() because l am obsessed with pretty printing, low-key OCD alert!!

True

In [ ]:
#to find the positional minimum
tf.argmin(rand)
rand[tf.argmin(rand)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#Squeezing tensors

In [ ]:

#reshape rand into a tensor of rank 5
rand = tf.constant(rand, shape = (1, 1, 1, 1, 50))
rand.ndim
rand.shape
tf.squeeze(rand) , tf.squeeze(rand).shape

#squeeze removes dimensions of size 1 from a tensor
#l used to do this using reshape, it's cool to know l can do this another way!



(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

#Encoding tensors


In [ ]:
#Create a list of indices
some_list = [0, 1, 2, 3]  #could be red, blue, green, black

#one-hot encode the list of indices above

tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one_hot encoding

tf.one_hot(some_list, depth = 4, on_value = "I miss him", off_value = "True")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I miss him', b'True', b'True', b'True'],
       [b'True', b'I miss him', b'True', b'True'],
       [b'True', b'True', b'I miss him', b'True'],
       [b'True', b'True', b'True', b'I miss him']], dtype=object)>

#Other tensor operations



*   tf.math.sqrt , method requires non-int argument
*   tf.math.square
*   tf.math.log , also requires non_int argument, see tensorflow documentation of allowed dtypes





#Tensors and Numpy

Tensorflow interacts beautifully with Numpy

In [ ]:
A = np.array([1.2, 7.8])
A

array([1.2, 7.8])

In [ ]:
#you can easily convert a numpy array into a tensor using tf.constant
A = tf.constant(A)
A


<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.2, 7.8])>

In [ ]:
#we can also easily convert a tensor back to a numpy array as follows:
np.array(A), type(np.array(A))

(array([1.2, 7.8]), numpy.ndarray)

In [ ]:
#the default datypes are slightly different  for tensors and numpy arrays
A = tf.constant(np.array([3.5, 1.7]))
print(A.dtype)
B = tf.constant([3.5, 1.7])
print(B.dtype)


#this is part of the reason why by default tensors run faster than numpy as tensors consume less memory

<dtype: 'float64'>
<dtype: 'float32'>


#Making sure our tensors really run faster than numpy on GPUs 

In [ ]:
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi #to check the type of GPU you got access to when you use google collab resources 
